name: Deploy to Beta Server
on:
  push:
    branches:
      - beta
env:
  ENGINE_URL: https://engine.festingervault.com
jobs:
  deploy:
    name: Beta Server Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_IP}} >> ~/.ssh/known_hosts
      - name: Install PHP and dependencies
        run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml
      - name: Install NPM Dependencies
        run: npm install && npm run namespace
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Build Scripts
        run: npm run deploy
      - name: RSync to Server
        run: |
          cd ./deploy
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ ${{secrets.SSH_USERNAME}}@${{secrets.SSH_IP}}:${{secrets.BASE_PATH}}
      - name: Clear SSH key
        run: rm ~/.ssh/id_rsa
