name: Beta Relase
on:
  push:
    branches:
      - beta
env:
  ENGINE_URL: https://engine.festingervault.com
jobs:
  deploy:
    name: Beta Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install PHP and dependencies
        run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml
      - name: Setup ENV files
        run: cp .env.beta .env
      - name: Install NPM Dependencies
        run: npm install && npm run namespace
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Build Scripts
        run: npm run build
      - name: Setup Crowdin file
        run: cp crowdin.github.yml crowdin.yml
      - name: Upload translations to Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          skip_untranslated_strings: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
      - name: Make JSON from PO Files
        run: npm run make-json
      - name: Build Trunk
        run: npm run dist
      - name: Release Trunk
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: beta-trunk
          FOLDER: deploy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ZIP and Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: beta-release
          FOLDER: dist
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
