name: Development
on:
  push:
    branches:
      - dev
env:
  ENGINE_URL: https://engine-dev.festingervault.com
jobs:
  deploy:
    name: Dev Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install PHP and dependencies
      run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml
    - name: Install NPM Dependencies
      run: npm install && npm run namespace
    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Build Scripts
      run: npm run release
    - name: Trunk
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dev-trunk
        FOLDER: deploy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: ZIP
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dev-release
        FOLDER: dist
        SQUASH_HISTORY: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
